//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC04.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_EF_firtsEntities1 : DbContext
    {
        public DB_EF_firtsEntities1()
            : base("name=DB_EF_firtsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    
        public virtual int ThemSanPham(string p_ProductName, string p_ImageURL, Nullable<decimal> p_ProductPrice, string p_Description)
        {
            var p_ProductNameParameter = p_ProductName != null ?
                new ObjectParameter("p_ProductName", p_ProductName) :
                new ObjectParameter("p_ProductName", typeof(string));
    
            var p_ImageURLParameter = p_ImageURL != null ?
                new ObjectParameter("p_ImageURL", p_ImageURL) :
                new ObjectParameter("p_ImageURL", typeof(string));
    
            var p_ProductPriceParameter = p_ProductPrice.HasValue ?
                new ObjectParameter("p_ProductPrice", p_ProductPrice) :
                new ObjectParameter("p_ProductPrice", typeof(decimal));
    
            var p_DescriptionParameter = p_Description != null ?
                new ObjectParameter("p_Description", p_Description) :
                new ObjectParameter("p_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemSanPham", p_ProductNameParameter, p_ImageURLParameter, p_ProductPriceParameter, p_DescriptionParameter);
        }
    }
}
