//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC04.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;
    public partial class tblProduct
    {
        public int ProductID { get; set; }
        [DisplayName("Product Name")]
        public string ProductName { get; set; }
        [DisplayName("Image upload")]
        public string ImageURL { get; set; }
        [DisplayName("Product Price")]
        public decimal ProductPrice { get; set; }
        [DisplayName("Description")]
        public string Description { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
