//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int iCartID { get; set; }
        public int iSL { get; set; }
        public int fk_iHangHoaID { get; set; }
    
        public virtual tblHanghoa tblHanghoa { get; set; }
    }
}
