//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC05.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_Shop4TrainingEntities : DbContext
    {
        public db_Shop4TrainingEntities()
            : base("name=db_Shop4TrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblChitiethoadon> tblChitiethoadons { get; set; }
        public virtual DbSet<tblHanghoa> tblHanghoas { get; set; }
        public virtual DbSet<tblHoadon> tblHoadons { get; set; }
        public virtual DbSet<tblKhachhang> tblKhachhangs { get; set; }
    }
}
