//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHanghoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHanghoa()
        {
            this.carts = new HashSet<cart>();
            this.tblChitiethoadons = new HashSet<tblChitiethoadon>();
        }
    
        public int PK_iHanghoaID { get; set; }
        public string sTenhang { get; set; }
        public double fGianiemyet { get; set; }
        public string sDacdiem { get; set; }
        public string sXuatxu { get; set; }
        public string sAnhminhhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChitiethoadon> tblChitiethoadons { get; set; }
    }
}
