//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoadon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoadon()
        {
            this.tblChitiethoadons = new HashSet<tblChitiethoadon>();
        }
    
        public int PK_iHoadonID { get; set; }
        public System.DateTime tNgaylap { get; set; }
        public int FK_iKhachhangID { get; set; }
        public System.DateTime tNgayGiaoHang { get; set; }
        public string sTennguoinhan { get; set; }
        public string sDiachigiaohang { get; set; }
        public string sDienthoaiNguoinhan { get; set; }
        public bool bDathanhtoan { get; set; }
        public string sNguoilapHoadon { get; set; }
        public double fTileGiamgia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChitiethoadon> tblChitiethoadons { get; set; }
        public virtual tblKhachhang tblKhachhang { get; set; }
    }
}
