//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC05.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKhachhang()
        {
            this.tblHoadons = new HashSet<tblHoadon>();
        }
    
        public int PK_iKhachhangID { get; set; }
        public string sHoten { get; set; }
        public string sDiachi { get; set; }
        public string sDienthoai { get; set; }
        public bool bGioitinh { get; set; }
        public System.DateTime tNgaysinh { get; set; }
        public string sTenCoquan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHoadon> tblHoadons { get; set; }
    }
}
